# This is a basic workflow to help you get started with Actions
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: mikedelgaudio/labeler@vMike
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
